credentials:
  usernames:
    ayonaryan:
      name: Ayon Aryan
      password: '$2b$12$VjwiXAIhNMUyCr/2xLQleOCSBC63okZ0RWPCV.1sSwX2NqKrO./Vy'

cookie:
  name: moodix_cookie
  key: some_signature_key
  expiry_days: 30
