credentials:
  usernames:
    ayonaryan:
      name: Ayon Aryan
      password: '$2b$12$BmGC2fQUBqTz.jaXwWujZuhmWMElnXBtEBoBd5UTc62mNtKA/2Ple'

cookie:
  name: moodix_cookie
  key: some_signature_key
  expiry_days: 30
